#%RAML 1.0 NamedExample

   {
            "accountNum": "1234567891",
            "atmPin": "1252",
            "ifscCode": "HDFC00022",
            "depoitAmount": 0,
            "mailId": "sasdfa@gmil.com",
            "contact": 256545258
          }